### ISSUE TITLE
Angular 2 -> 4 conversion

### ISSUE THREAD

**Issue by mattrpav** [atlasmap/atlasmap-ui#2]

**Comment by jbakermd** [comment]
Hey @gashcrumb  & @kahboom,

@mattrpav and I just spoke and I'll be prioritizing integrating the datamapper ui back into the syndesis ui over the next couple of days. 

There are a couple of steps to this process:

a) I'll drop the latest code into the repo here.

b) We need to merge @gashcrumb's library upgrade commits for this issue: https://github.com/syndesisio/syndesis-datamapper-ui/issues/67. 

c) Step b is going to lead to some functionality breakage from the ngx-bootstrap upgrade, so I'll need to dig into those. A quick upgrade attempt a few months back broke tooltips and/or typeahead usages.

d) Standing up the datamapper UI requires a few more services from the atlas.services project than the redhat summit demo needed. This is probably why you are having problems trying to get the latest datamapper UI off the ground as a standalone project. 

e) The integration point between syndesis and the datamapper UI will need some changes. There are definitely some new complications here: new service endpoints, new document formats (XML/JSON), and other small configurable flags. 

f) CSS issues that crop up between the datamapper ui and the latest syndesis UI will need to be fixed. 

@kahboom, Matt mentioned that you might already be attempting to integrate the data mapper UI into the current syndesis UI. Let's sync up on what you've done and how we can move forward.

**Comment by gashcrumb** [comment]
Makes sense to me!

@rhuss @chirino have we deployed the updated data mapper backend stuff to staging by any chance?

**Comment by kahboom** [comment]
That's perfect @mattrpav , thanks! It makes sense, to me, to break up those steps into multiple issues so that they can be tracked from here, since it's likely we will have user stories that are dependent on the mapper: https://github.com/syndesisio/syndesis-ui/issues#boards

@jbakermd - Not at the moment, since I am currently working on two other issues. However, I'd be glad to sync up so that we can all be on the same page and I can help @gashcrumb with anything he might need. Set up a meeting for whenever works best for you and I'd be happy to attend.

**Comment by jbakermd** [comment]
Ok. Let me get some obvious bits of the process out of the way on my end, then we can discuss the integration from both the datamapper side and the syndesis side. I will update the libs, fix breakages, and clean up a bit of the config for fault tolerance when non-critical services aren't available. 

@gashcrumb / @rhuss  / @chirino : The data mapper services have a few new data mapper services that the UI relies on. I believe for the summit demo we only had the java inspection service available. Now there are several more: the XML inspection service, the JSON inspection service, and the mapping service (which provides field action configuration and mapping engine validation rules).  @mattrpav can provide guidance on standing these up.

**Comment by jbakermd** [comment]
Ok there are a few things remaining now:

a) integrate back into the syndesis UI

b) address CSS fixes and any other issues that result from step A, such as those random settimeout() calls we need every so often.

c) Stand up additional services for data mapper. The UI is now fault tolerant in this regard and can run without these services until they are available.

**Comment by jbakermd** [comment]
@gashcrumb in terms of integration into the syndesis UI, do I just fetch the latest from https://github.com/syndesisio/syndesis-ui, yarn install, and run again? 

Are there any major changes on the integration point for data mapper? 

Is the integration point still the same class as before?

**Comment by gashcrumb** [comment]
Yep, that's about it, no major changes in that page yet since summit, so
fingers crossed it should mostly be a matter of updating the git URL in the
package.json mostly, plus updating any initialization code as needed.  I
can give that a look tomorrow.

On Jul 11, 2017 5:12 PM, "Jason Baker" <notifications@github.com> wrote:

@gashcrumb <https://github.com/gashcrumb> in terms of integration into the
syndesis UI, do I just fetch the latest from https://github.com/syndesisio/
syndesis-ui, yarn install, and run again?

Are there any major changes on the integration point for data mapper?

Is the integration point still the same class as before?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/atlasmap/atlasmap-ui/issues/2#issuecomment-314573341>,
or mute the thread

**Comment by jbakermd** [comment]
Ok sounds good. I can do a first pass of the integration if you don't mind. I'll leave some comments inline and update this ticket on what needs to be cleaned up or changed for further support such as JSON/XML document input and such.

**Comment by rhuss** [comment]
@gashcrumb @mattrpav @jbakermd @chirino For staging and development we are currently using the Docker image `atlasmap/syndesis-datamapper` which is build and pushed automatically by a CircelCI job on https://github.com/syndesisio/syndesis-datamapper. 

I can try to setup a similar build on https://github.com/atlasmap/atlasmap and would change then the image name to `atlasmap/atlasmap`.

However I wonder about the security setup:

* Who owns the `atlasmap` used on Docker Hub ? As I see from the Circleci configuration, the image pushed under the user `chirino` and some password. I just created a Docker user `syndesisio`, would be awesome if we could at them to have push access to `atlasmap`, too.
* I would need to get access to the `atlasmap` organization for integrating circleci. An access request has been sent out.

If this is given, I can copy over the current build mechanism, which will create a `latest` images on Dockerhub for every commit + versioned Docker images for each tag.

**Comment by mattrpav** [comment]
CircleCi has beengranted access.

 I haven't been involved with any of the Docker work. Probably need to ping Hiram.

**Comment by gashcrumb** [comment]
> Ok sounds good. I can do a first pass of the integration if you don't mind. I'll leave some comments inline and update this ticket on what needs to be cleaned up or changed for further support such as JSON/XML document input and such.

Perfect!  Let me know if you need anything.

**Comment by chirino** [comment]
@rhuss sounds good.  Let me know if you need any help with the circle ci builds.

**Comment by jbakermd** [comment]
Ok the initial integration between the syndesis ui and the latest data mapper ui is ready. I'm going to hold off on a pull request until these new data mapper services are available on staging environment.

I've created a syndesis side ticket regarding the new services:

https://github.com/syndesisio/syndesis-ui/issues/603

The initial ui integration work is on this fork:

https://github.com/jbakermd/syndesis-ui

I've created this integration ticket over on the syndesis side to track various remaining integration tasks:

https://github.com/syndesisio/syndesis-ui/issues/602

**Comment by gashcrumb** [comment]
Think if the work is done getting the dependencies synced up I think we can close this issue and track the remaining work to get it all integrated  in https://github.com/atlasmap/atlasmap/issues/13 and https://github.com/syndesisio/syndesis-ui/issues/602

**Comment by jbakermd** [comment]
agree. closing.
